### ISSUE TITLE
Remove src/main/resources/META-INF/spring-devtools.properties from final build

### ISSUE THREAD

**Issue by migueltercero** [akkinoc/orika-spring-boot-starter#12]
### Problem
Can´t autowire MapperFacade in other starter when test application with devtools

### Solution
Remove src/main/resources/META-INF/spring-devtools.properties from final build. User for example maven resources plugin to exclude file or add to gitignore.

**Comment by akkinoc** [comment]
Thank you for your report. Sorry for the late reply.
I removed the "META-INF / spring-devtools.properties" file and released it in v2.0.0!
