### ISSUE TITLE
orika jdk11 problem, An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by evanyangg** [akkinoc/orika-spring-boot-starter#156]
hello guys, do you know the cause of this problem?
I just switched the version of jdk，I don't know if orika supports jdk11 or not

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ma.glasnost.orika.converter.builtin.CloneableConverter (file:/Users/sun/.gradle/caches/modules-2/files-2.1/ma.glasnost.orika/orika-core/1.5.4/b4f1019bfeda6d6aa0790a42f2d317151d2d2f4d/orika-core-1.5.4.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of ma.glasnost.orika.converter.builtin.CloneableConverter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

orika-spring-boot-starter 2.4.3
springboot  2.6.3
jdk  zulu-11.jdk

**Comment by akkinoc** [comment]
It works on Java 11, but as you mentioned, a warning message is displayed.
I believe that the warning can be suppressed by adding this JVM option: `--add-opens java.base/java.lang=ALL-UNNAMED`

ref) https://github.com/orika-mapper/orika/issues/280

**Comment by akkinoc** [comment]
This issue is not active, so I will close it.
If you still have problems, please open a new issue.
